services:
  app:
    # Obraz jest wstrzykiwany przez GitHub Actions
    image: ${IMAGE_NAME} 
    container_name: ${CONTAINER_NAME} # Opcjonalnie, dla czytelności w QNAP
    restart: unless-stopped
    ports:
      # Port hosta jest wstrzykiwany przez Port Huntera
      - "${HOST_PORT}:8000" 
    environment:
      - NODE_ENV=production
      - OPENAI_API_KEY=${OPENAI_API_KEY}